### ISSUE TITLE
Fehler unter Linux.

### ISSUE THREAD

**Issue by m4z** [Hyso/adef#4]
Hey,
erst dachte ich, ich hätte den Code kaputtgespielt, aber nachdem ich jetzt nochmal deine alte Version ausgecheckt hab, und alle
"from enthought.mayavi import mlab"

ersetzt habe durch 

"try:
        from enthought.mayavi import mlab
except ImportError:
        from mayavi import mlab"

(das ist nötig, damit das bei mir läuft), ist der Code trotzdem kaputt (siehe unten).
Ich bin grad noch zu dumm das zu debuggen, meinst du das könnte sein weil ich evtl. andere Versionen von Mayavi (Mayavi version 4.0.0 - VTK version 5.6.1), Traits (python-traits 4.0.0-1) oder python (Python 2.7.2+ 
wxPython 2.8.11.0) benutze?

Der Fehler sieht so aus (sobald ich eine Kurve gelegt habe und auf "Kurve berechnen" klicke:
---------- 8< ----------
Exception occurred in traits notification handler for object: <extentDialog.ExtentDialog object at 0xad71fbc>, trait: Kurve, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 505, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 448, in dispatch
    handler( _args )
  File "extentDialog.py", line 109, in update_kurve
    self.myobj.kurve_berechnen()
  File "myobject.py", line 226, in kurve_berechnen
    self.d,self.e,self.f = self.dKtt(self.t, self.tckp)
  File "myobject.py", line 149, in <lambda>
    dKtt = lambda self,t,tckp: array([self.dxuu(u(t,tckp),v(t,tckp)),self.dyuu(u(t,tckp),v(t,tckp)),self.dzuu(u(t,tckp),v(t,tckp))])_du(t,tckp) + 2_(array([self.dxuv(u(t,tckp),v(t,tckp)),self.dyuv(u(t,tckp),v(t,tckp)),self.dzuv(u(t,tckp),v(t,tckp))]))_du(t,tckp)_dv(t,tckp) + array([self.dxu(u(t,tckp),v(t,tckp)),self.dyu(u(t,tckp),v(t,tckp)),self.dzu(u(t,tckp),v(t,tckp))])_duu(t,tckp) + array([self.dxvv(u(t,tckp),v(t,tckp)),self.dyvv(u(t,tckp),v(t,tckp)),self.dzvv(u(t,tckp),v(t,tckp))])_dv(t,tckp) + array([self.dxv(u(t,tckp),v(t,tckp)),self.dyv(u(t,tckp),v(t,tckp)),self.dzv(u(t,tckp),v(t,tckp))])_dvv(t,tckp)
ValueError: setting an array element with a sequence.
ERROR|2012-05-10 14:27:11,476|Exception occurred in traits notification handler for object: <extentDialog.ExtentDialog object at 0xad71fbc>, trait: Kurve, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 505, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 448, in dispatch
    handler( _args )
  File "extentDialog.py", line 109, in update_kurve
    self.myobj.kurve_berechnen()
  File "myobject.py", line 226, in kurve_berechnen
    self.d,self.e,self.f = self.dKtt(self.t, self.tckp)
  File "myobject.py", line 149, in <lambda>
    dKtt = lambda self,t,tckp: array([self.dxuu(u(t,tckp),v(t,tckp)),self.dyuu(u(t,tckp),v(t,tckp)),self.dzuu(u(t,tckp),v(t,tckp))])_du(t,tckp) + 2_(array([self.dxuv(u(t,tckp),v(t,tckp)),self.dyuv(u(t,tckp),v(t,tckp)),self.dzuv(u(t,tckp),v(t,tckp))]))_du(t,tckp)_dv(t,tckp) + array([self.dxu(u(t,tckp),v(t,tckp)),self.dyu(u(t,tckp),v(t,tckp)),self.dzu(u(t,tckp),v(t,tckp))])_duu(t,tckp) + array([self.dxvv(u(t,tckp),v(t,tckp)),self.dyvv(u(t,tckp),v(t,tckp)),self.dzvv(u(t,tckp),v(t,tckp))])_dv(t,tckp) + array([self.dxv(u(t,tckp),v(t,tckp)),self.dyv(u(t,tckp),v(t,tckp)),self.dzv(u(t,tckp),v(t,tckp))])_dvv(t,tckp)
ValueError: setting an array element with a sequence.
---------- >8 ----------

**Comment by Hyso** [comment]
hallo hilmi,auf welcher der gekrümmten flächen hast du den versucht die kurve zu legen?bei zwei flächen funktioniert es nur soweit, dass du die punkte selektieren kannst, aber die berechnung der kurve und die ganzen eigenschaften funktioniert nicht und kommt eine fehlermeldung.die zwei flächen bei denen die berechnung der eigenschaften nicht funktioniert sind:parabolischer zylinder und hyperbolisches paraboloid.gruß,hüseyin

```
    Gesendet: Donnerstag, 10. Mai 2012 um 14:37 UhrVon: "Christopher Holm" <reply@reply.github.com>An: Hyso <hasan_hh@web.de>Betreff: [adef] Fehler unter Linux. (#4)


    Hey,
```

erst dachte ich, ich hätte den Code kaputtgespielt, aber nachdem ich jetzt nochmal deine alte Version ausgecheckt hab, und alle
"from enthought.mayavi import mlab"
ersetzt habe durch 
"try:
        from enthought.mayavi import mlab
except ImportError:
        from mayavi import mlab"
(das ist nötig, damit das bei mir läuft), ist der Code trotzdem kaputt (siehe unten).
Ich bin grad noch zu dumm das zu debuggen, meinst du das könnte sein weil ich evtl. andere Versionen von Mayavi (Mayavi version 4.0.0 - VTK version 5.6.1), Traits (python-traits 4.0.0-1) oder python (Python 2.7.2+ 
wxPython 2.8.11.0) benutze?
Der Fehler sieht so aus (sobald ich eine Kurve gelegt habe und auf "Kurve berechnen" klicke:
---------- 8< ----------
Exception occurred in traits notification handler for object: <extentDialog.ExtentDialog object at 0xad71fbc>, trait: Kurve, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 505, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 448, in dispatch
    handler( _args )
  File "extentDialog.py", line 109, in update_kurve
    self.myobj.kurve_berechnen()
  File "myobject.py", line 226, in kurve_berechnen
    self.d,self.e,self.f = self.dKtt(self.t, self.tckp)
  File "myobject.py", line 149, in <lambda>
    dKtt = lambda self,t,tckp: array([self.dxuu(u(t,tckp),v(t,tckp)),self.dyuu(u(t,tckp),v(t,tckp)),self.dzuu(u(t,tckp),v(t,tckp))])_du(t,tckp) + 2_(array([self.dxuv(u(t,tckp),v(t,tckp)),self.dyuv(u(t,tckp),v(t,tckp)),self.dzuv(u(t,tckp),v(t,tckp))]))_du(t,tckp)_dv(t,tckp) + array([self.dxu(u(t,tckp),v(t,tckp)),self.dyu(u(t,tckp),v(t,tckp)),self.dzu(u(t,tckp),v(t,tckp))])_duu(t,tckp) + array([self.dxvv(u(t,tckp),v(t,tckp)),self.dyvv(u(t,tckp),v(t,tckp)),self.dzvv(u(t,tckp),v(t,tckp))])_dv(t,tckp) + array([self.dxv(u(t,tckp),v(t,tckp)),self.dyv(u(t,tckp),v(t,tckp)),self.dzv(u(t,tckp),v(t,tckp))])_dvv(t,tckp)
ValueError: setting an array element with a sequence.
ERROR|2012-05-10 14:27:11,476|Exception occurred in traits notification handler for object: <extentDialog.ExtentDialog object at 0xad71fbc>, trait: Kurve, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 505, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 448, in dispatch
    handler( _args )
  File "extentDialog.py", line 109, in update_kurve
    self.myobj.kurve_berechnen()
  File "myobject.py", line 226, in kurve_berechnen
    self.d,self.e,self.f = self.dKtt(self.t, self.tckp)
  File "myobject.py", line 149, in <lambda>
    dKtt = lambda self,t,tckp: array([self.dxuu(u(t,tckp),v(t,tckp)),self.dyuu(u(t,tckp),v(t,tckp)),self.dzuu(u(t,tckp),v(t,tckp))])_du(t,tckp) + 2_(array([self.dxuv(u(t,tckp),v(t,tckp)),self.dyuv(u(t,tckp),v(t,tckp)),self.dzuv(u(t,tckp),v(t,tckp))]))_du(t,tckp)_dv(t,tckp) + array([self.dxu(u(t,tckp),v(t,tckp)),self.dyu(u(t,tckp),v(t,tckp)),self.dzu(u(t,tckp),v(t,tckp))])_duu(t,tckp) + array([self.dxvv(u(t,tckp),v(t,tckp)),self.dyvv(u(t,tckp),v(t,tckp)),self.dzvv(u(t,tckp),v(t,tckp))])_dv(t,tckp) + array([self.dxv(u(t,tckp),v(t,tckp)),self.dyv(u(t,tckp),v(t,tckp)),self.dzv(u(t,tckp),v(t,tckp))])_dvv(t,tckp)
ValueError: setting an array element with a sequence.

## ---------- >8 ----------

Reply to this email directly or view it on GitHub:https://github.com/Hyso/adef/issues/4
  Ihr WEB.DE Postfach immer dabei: die kostenlose WEB.DE Mail App für iPhone und Android.   https://produkte.web.de/freemail_mobile_startseite/

**Comment by m4z** [comment]
Ah, danke, das Detail hatte ich schon wieder vergessen! Das war die erste Fläche in der Liste, also der p.Z. glaube ich. Ich bastel da noch ein bisschen dran rum und dann schliesse ich das Ticket hier in einigen Tagen selbst.
